-- Add short locate status enum
CREATE TYPE "ShortLocateStatus" AS ENUM ('NOT_REQUIRED', 'REQUESTED', 'CONFIRMED', 'EXPIRED');

ALTER TABLE "Order"
ADD COLUMN IF NOT EXISTS "shortLocateStatus" "ShortLocateStatus" NOT NULL DEFAULT 'NOT_REQUIRED',
ADD COLUMN IF NOT EXISTS "shortLocateId" TEXT,
ADD COLUMN IF NOT EXISTS "shortLocateQuantity" INTEGER,
ADD COLUMN IF NOT EXISTS "shortBorrowRateCapPct" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "shortBorrowRatePct" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "shortLocateProvider" TEXT,
ADD COLUMN IF NOT EXISTS "shortLocateRequestedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "shortLocateRespondedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "shortLocateExpiresAt" TIMESTAMP(3);
